# Generated by Django 4.2.4 on 2023-10-11 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster_label', models.IntegerField(default=-1)),
                ('cluster_num', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='comments',
            name='cluster_label',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='comments',
            name='display',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='cluster_num',
            field=models.IntegerField(default=-1),
        ),
    ]
