# Generated by Django 4.2.4 on 2023-10-11 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0002_cluster_comments_cluster_label_comments_display_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cluster',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='cluster_label',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='display',
        ),
        migrations.RemoveField(
            model_name='user',
            name='cluster_num',
        ),
    ]
