# Generated by Django 4.2.4 on 2023-10-15 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0003_delete_cluster_remove_comments_cluster_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='cluster_dispaly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comments',
            name='cluster_label',
            field=models.IntegerField(default=-1),
        ),
    ]
