# Generated by Django 4.2.4 on 2023-10-15 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0004_comments_cluster_dispaly_comments_cluster_label'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='cluster_dispaly',
            new_name='cluster_display',
        ),
    ]
