# Generated by Django 4.2.4 on 2023-11-15 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0005_rename_cluster_dispaly_comments_cluster_display'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='anti',
            field=models.BooleanField(default=False),
        ),
    ]
