# Generated by Django 4.2.4 on 2023-12-04 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0006_comments_anti'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='anti',
            new_name='anti_display',
        ),
        migrations.AddField(
            model_name='comments',
            name='anti_label',
            field=models.BooleanField(default=False),
        ),
    ]
