# Generated by Django 4.2.4 on 2023-12-05 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0007_rename_anti_comments_anti_display_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='anti_display',
        ),
    ]
