# Generated by Django 4.2.4 on 2023-12-13 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0010_comments_anti_display_comments_cluster_display_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='anti_label',
            field=models.FloatField(default=0.0),
        ),
    ]
