# Generated by Django 4.2.4 on 2023-12-13 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0011_alter_comments_anti_label'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='anti_label',
            new_name='anti_violence_score',
        ),
    ]
