# Generated by Django 4.2.4 on 2024-01-10 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0013_user_useopenaiapi_alter_comments_anti_display_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='commentFastMode',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='user',
            name='commentFilterLevel',
            field=models.IntegerField(default=2),
        ),
    ]
